ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (SERVICE_PROVIDER VARCHAR2(30 CHAR) NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (ID_OLT NUMBER NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (OLT VARCHAR2(60 CHAR) NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (CTO VARCHAR2(60 CHAR) NULL);
