---------------------------------------------------------------------------------------------------
-- ~~~~~~~~~~~~~~~~~~                CVLAN                                       ~~~~~~~~~~~~~~~~~~
---------------------------------------------------------------------------------------------------

-- ~~~~~~~~~~~~~~~~~~~~~~~ RETIRADA DOS NOT NULLS ~~~~~~~~~~~~~~~~~~~~~~~
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (SERVICE_PROVIDER VARCHAR2(30 CHAR) NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (ID_OLT NUMBER NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (OLT VARCHAR2(60 CHAR) NULL);
ALTER TABLE MIG_BLOCKED_CVLAN MODIFY (CTO VARCHAR2(60 CHAR) NULL);
-- ~~~~~~~~~~~~~~~~~~~~~~~ INSERÇÃO DE NOVAS COLUNAS ~~~~~~~~~~~~~~~~~~~~~~~
ALTER TABLE MIG_BLOCKED_CVLAN ADD UID_OLT VARCHAR2(30);
ALTER TABLE MIG_BLOCKED_CVLAN ADD CTL_NAME VARCHAR2(30);
ALTER TABLE MIG_BLOCKED_CVLAN ADD CTL_CIDADE_SIGLA VARCHAR2(30);
ALTER TABLE MIG_BLOCKED_CVLAN ADD INTERFACE_PON VARCHAR2(30);
ALTER TABLE MIG_BLOCKED_CVLAN ADD IS_BLOCKED NUMBER(1) DEFAULT 1;
-- ~~~~~~~~~~~~~~~~~~~~~~~ ADD PRIMARY KEY ~~~~~~~~~~~~~~~~~~~~~~~
ALTER TABLE MIG_BLOCKED_CVLAN ADD ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY;
ALTER TABLE MIG_BLOCKED_CVLAN ADD CONSTRAINT teste PRIMARY KEY (ID); -- Mudar nome teste
-- ~~~~~~~~~~~~~~~~~~~~~~~ CRIANDO TABELA DE AUDITORIA ~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE AUDIT_LOG_MIG_BLOCK_CVLAN (
    ID              NUMBER,
    USER_CREATED    VARCHAR2(50 CHAR)   NOT NULL,
    DATE_CREATED    TIMESTAMP           NOT NULL,
    OPERATION       VARCHAR2(20 CHAR)   NOT NULL,
    SYSTEM          VARCHAR2(50 CHAR)   NOT NULL,
    COMMENTS        VARCHAR2(200 CHAR)          ,
    PROCESS_ID      NUMBER
);
-- ~~~~~~~~~~~~~~~~~~~~~~~ CRIANDO TABELA DE AUDITORIA ~~~~~~~~~~~~~~~~~~~~~~~
ALTER TABLE AUDIT_LOG_MIG_BLOCK_CVLAN ADD CONSTRAINT pk_audit_log_mig_block_cvlan PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_AUDIT_LOG_MIG_BLOCK_CVLAN start with 1 increment by 1 nocache;


---------------------------------------------------------------------------------------------------
-- ~~~~~~~~~~~~~~~~~~                  ONT                                       ~~~~~~~~~~~~~~~~~~
---------------------------------------------------------------------------------------------------


-- ~~~~~~~~~~~~~~~~~~~~~~~ CRIANDO TABELA DE AUDITORIA ~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE AUDIT_LOG_MIG_BLOCK_ONT (
    ID                      NUMBER,
    USER_CREATED            VARCHAR2(50 CHAR)   NOT NULL,
    DATE_CREATED            TIMESTAMP           NOT NULL,
    STATE_ABBREVIATION      VARCHAR(2),
    STATE_NAME              VARCHAR(50),
    LOCALITY_ABBREVIATION   VARCHAR(5),
    LOCALITY_NAME           VARCHAR(100),
    OLT_NAME                VARCHAR(100),
    OLT_UID                 VARCHAR(50),
    PON_INTERFACE           VARCHAR(50)         NOT NULL,
    ONT_ID                  NUMERIC             NOT NULL,
    BLOCK_REASON            VARCHAR(100)        NOT NULL,
    OPERATION               VARCHAR2(20 CHAR)   NOT NULL,
    SYSTEM                  VARCHAR2(50 CHAR)   NOT NULL,
    COMMENTS                VARCHAR2(200 CHAR)          ,
    PROCESS_ID              NUMBER
);

ALTER TABLE AUDIT_LOG_MIG_BLOCK_ONT ADD CONSTRAINT pk_audit_log_mig_block_ont PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_AUDIT_LOG_MIG_BLOCK_ONT start with 1 increment by 1 nocache;
